kind: pipeline
name: amd64

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

environment:
  GOOS: linux
  GOARCH: amd64

steps:
  - name: build
    image: golang:latest
    commands:
      - go build -o cloudflare-ddns-$${GOOS}-$${GOARCH} ./... 

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
         from_secret: gitea_token
      base_url: https://git.wasil.org
      files:
        - cloudflare-ddns-$${GOOS}-$${GOARCH}
      title: 0.0.4
      note: test 1
    when:
      event: tag

# ---
# kind: pipeline
# name: amrv7

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: build
#   image: golang:latest
#   commands:
#     - go mod tidy
#     - go build ./...
#   environment:
#     GOOS: linux
#     GOARCH: arm
#     GOARM: 7

# - name: github_release
#   pull: default
#   image: plugins/github-release
#   settings:
#     files:
#       from_secret: ""
#       value:
#       - "/go/bin/*"
#   environment:
#     GITHUB_TOKEN:
#       from_secret: github_token
#   when:
#     event:
#     - tag
