kind: pipeline
name: build & deploy

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

steps:
  - name: linux amd64
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      - go build -o dist/cloudflare-ddns-$${GOOS}-$${GOARCH} ./... 

  - name: linux armv7
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
    commands:
      - go build -o dist/cloudflare-ddns-$${GOOS}-$${GOARCH}v$${GOARM} ./... 

  - name: deploy to gitea
    image: plugins/gitea-release
    settings:
      api_key:
         from_secret: gitea_token
      base_url: https://git.wasil.org
      files:
        - /drone/src/dist/*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
      title: 0.0.10
    when:
      event: tag
    depends_on:
      - linux amd64
      - linux armv7
