kind: pipeline
type: docker
name: build & deploy

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

steps:
  - name: linux amd64
    image: quay.io/wasilak/golang:1.16-alpine
    pull: if-not-exists
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      - go build -o dist/cloudflare-ddns-$${GOOS}-$${GOARCH}

  - name: osx amd64
    image: quay.io/wasilak/golang:1.16-alpine
    pull: if-not-exists
    environment:
      GOOS: darwin
      GOARCH: amd64
    commands:
      - go build -o dist/cloudflare-ddns-$${GOOS}-$${GOARCH}

  - name: linux armv7
    image: quay.io/wasilak/golang:1.16-alpine
    pull: if-not-exists
    environment:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
    commands:
      - go build -o dist/cloudflare-ddns-$${GOOS}-$${GOARCH}v$${GOARM}

  - name: linux arm64
    image: quay.io/wasilak/golang:1.16-alpine
    pull: if-not-exists
    environment:
      GOOS: linux
      GOARCH: arm64
    commands:
      - go build -o dist/cloudflare-ddns-$${GOOS}-$${GOARCH}

  - name: deploy to gitea
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_token
      base_url: http://git.service.consul
      files:
        - /drone/src/dist/*
      title: 0.0.14
      note: CHANGELOG_LAST.md # git changelog -s 0.0.13 -f 0.0.13 -l -p CHANGELOG_LAST.md
      # note: CHANGELOG.md # git changelog -a -p CHANGELOG.md
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event: tag
    depends_on:
      - osx amd64
      - linux amd64
      - linux armv7
      - linux arm64
